[colors.primary]
background = "0x000000"
foreground = "0xD3D3D3"

[font]
size = 24 

[cursor.style]
blinking = "Always"

[cursor]
blink_interval = 500

[font.normal]
family = "GohuFont 14 Nerd Font"
style = "Regular"

[terminal]

[terminal.shell]
program = "/usr/bin/zsh"

[window]
opacity = 1 
