
[colors.primary]
background = "0x000000"
foreground = "0xD3D3D3"

[font]
size = 24 

[font.normal]
family = "AdwaitaMono Nerd Font"
style = "Regular"

[terminal]

[terminal.shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.5
